### ISSUE TITLE
Thank you so much!!!

### ISSUE THREAD

**Issue by liucan89096** [donothingloop/ng2-charts-x#1]
I struggled with the valor-software/ng2-charts for a couple of days until I saw your comments on https://github.com/valor-software/ng2-charts/issues/806 and tried this library. You really have fixed quite a lot of things. Thank you very much!!! :)

**Comment by liucan89096** [comment]
btw, this is not an issue, I just want to appreciate your work.

**Comment by donothingloop** [comment]
Thank you! Closing this now.
